namespace PusulaEHealthSync.Mapping;

// Pusula SKRS "Yerlesim Yeri" ic kodu -> ICD-O-3 (XBT-O-3) topografya kodu.
//
// NEDEN BU HARITA VAR: az-pathology-finding profilinde component:topography 1..1 ZORUNLU ve
// required binding ile http://fhir.az/ValueSet/icd-o-3-topography-vs'e bagli (o da
// http://fhir.az/CodeSystem/az-icd-o-3 icinden "^C.*" regex'i ile suzuluyor -- IG'den
// dogrulandi 2026-09-08). Pusula bu bilgiyi [EMR.Pathology].[EPulse].YerlesimYeriCode
// alaninda tutuyor ama orada Turkiye'nin ulusal referans sunucusunun ("SKRS") IC kodu var
// (orn. "1212"), ICD-O-3 degil. Pusula veritabaninda cevirici bir tablo YOK:
// Skrs.YerlesimYeri.TopografikKodu ve Ortak.HizmetPatolojiOzellik.YerlesimYeriSkrsKodu
// kolonlari tam bu is icin duruyor ama IKISI DE 0 satir -- hic doldurulmamis.
//
// NASIL URETILDI: canli veride ([EMR.Pathology].[EPulse], ~52.000 kayit, 2022-09'dan
// bugune) kullanilmis 227 farkli topografya teriminin WHO ICD-O-3 listesindeki karsiligi
// alt-kategori yapisina gore tek tek belirlendi. "BBT" (Baska Turlu Belirtilmemis) tutarli
// olarak ICD-O-3'un ".9 NOS" ekine karsilik geliyor. Ayrintili gerekce ve tam tablo:
// docs/patoloji-topografya-icdo3-eslestirme.md
//
// TASLAK UYARISI: bu eslestirme HENUZ CANLI DOGRULANMADI. Yanlis bir eslesme, yanlis
// organ/bolge kodu gondermek demektir (tibbi veri kalitesi sorunu). Dokumanda "!" ile
// isaretli 6 satir ekstra dikkat ister.
//
// KAPSAM (2026-09-08 olculdu): onayli + neoplazili raporlarda gecen 158 farkli topografya
// kodunun TAMAMI bu tabloda var -- canli veride acik yok. Yine de bilinmeyen bir kod
// gelirse TryGet false doner ve cagiran taraf Skip eder; ASLA tahmin edilmez (ayni temkinli
// ilke: PathologyReportMapper'daki 400 karakter filtresi).
public static class PathologyTopographyMap
{
    // Anahtar: EPulse.YerlesimYeriCode (SKRS ic kodu). Deger: ICD-O-3 topografya kodu.
    // Yorumlar Pusula'daki Turkce terim -- gozden gecirmeyi kolaylastirmak icin.
    // Siralama: canli veride gorulme sikligina gore (en sik kullanilanlar ustte).
    private static readonly Dictionary<string, string> SkrsToIcdO3 = new()
    {
        ["1212"] = "C50.9", // Meme, BBT -> Breast, NOS (8867)
        ["1222"] = "C53.9", // Serviks uteri -> Cervix uteri, NOS (5244)
        ["1082"] = "C16.9", // Mide, BBT -> Stomach, NOS (4143)
        ["1255"] = "C64.9", // Böbrek, BBT -> Kidney, NOS (3987)
        ["1316"] = "C76.2", // Abdomen, BBT -> Abdomen, NOS (3175)
        ["1143"] = "C34.9", // Akciğer, BBT -> Lung, NOS (2347)
        ["1168"] = "C42.1", // Kemik iliği -> Bone marrow (2329)
        ["1097"] = "C18.9", // Kolon, BBT -> Colon, NOS (2258)
        ["1329"] = "C77.9", // Lenf düğümü, BBT -> Lymph nodes, NOS (1816)
        ["1105"] = "C22.0", // Karaciğer -> Liver (1645)
        ["1181"] = "C44.9", // Deri, BBT -> Skin, NOS (1288)
        ["1224"] = "C54.1", // Endometrium -> Endometrium (930)
        ["1246"] = "C61.9", // Prostat bezi -> Prostate gland (921)
        ["1229"] = "C55.9", // Uterus, BBT -> Uterus, NOS (921)
        ["1291"] = "C71.9", // Beyin, BBT -> Brain, NOS (669)
        ["1166"] = "C41.9", // Kemik, BBT -> Bone, NOS (669)
        ["1220"] = "C53.1", // Ekzoserviks -> Exocervix (619)
        ["1119"] = "C25.9", // Pankreas, BBT -> Pancreas, NOS (425)
        ["1267"] = "C67.9", // Mesane, BBT -> Bladder, NOS (415)
        ["1230"] = "C56.9", // Ovaryum -> Ovary (381)
        ["1302"] = "C73.9", // Thyroid bezi -> Thyroid gland (369)
        ["1314"] = "C76.0", // Baş, yüz ya da boyun, BBT -> Head, face or neck, NOS (349)
        ["1199"] = "C49.9", // Bağ dokusu, subkutan doku ve diğer yumuşak dokular, BBT -> Connective/soft tissue, NOS (347)
        ["1150"] = "C38.4", // Plevra, BBT -> Pleura, NOS (335)
        ["1315"] = "C76.1", // Göğüs/Toraks -> Thorax, NOS (329)
        ["1107"] = "C23.9", // Safra kesesi -> Gallbladder (329)
        ["1083"] = "C17.0", // Duodenum -> Duodenum (311)
        ["1073"] = "C15.9", // Özofagus, BBT -> Esophagus, NOS (296)
        ["1219"] = "C53.0", // Endoserviks -> Endocervix (283)
        ["1208"] = "C50.4", // Memenin üst-dış kadranı -> Upper-outer quadrant of breast (274)
        ["1100"] = "C20.9", // Rektum, BBT -> Rectum, NOS (265)
        ["1202"] = "C48.2", // Periton, BBT -> Peritoneum, NOS (256)
        ["1305"] = "C74.9", // Adrenal bez, BBT -> Adrenal gland, NOS (225)
        ["1095"] = "C18.7", // Sigmoid kolon -> Sigmoid colon (223)
        ["1249"] = "C62.9", // Testis, BBT -> Testis, NOS (221)
        ["1148"] = "C38.3", // Mediasten, BBT -> Mediastinum, NOS (204)
        ["1076"] = "C16.2", // Mide korpusu -> Body of stomach (178)
        ["1225"] = "C54.2", // Miyometrium -> Myometrium (168)
        ["1191"] = "C49.0", // Baş, yüz ve boyun bağ dokusu... -> Connective/soft tissue of head, face, neck (164)
        ["1099"] = "C18.1", // Appendiks -> Appendix (162)
        ["1322"] = "C77.0", // Baş, yüz ve boyun lenf düğümleri -> Lymph nodes of head, face, neck (141)
        ["1088"] = "C17.9", // İnce barsak, BBT -> Small intestine, NOS (141)
        ["1217"] = "C52.9", // Vagina, BBT -> Vagina (138)
        ["1195"] = "C49.4", // Abdomen bağ dokusu... -> Connective/soft tissue of abdomen (132)
        ["1094"] = "C18.6", // Desendan kolon -> Descending colon (130)
        ["1198"] = "C49.8", // Bağ dokusu...aşan lezyon -> Overlapping lesion of connective/soft tissue (118)
        ["1090"] = "C18.2", // Asenden kolon -> Ascending colon (116)
        ["1303"] = "C74.0", // Adrenal bez korteksi -> Cortex of adrenal gland (110)
        ["1282"] = "C70.1", // Spinal meninksler -> Spinal meninges (106)
        ["1138"] = "C34.0", // Ana bronşlar -> Main bronchus (103)
        ["1317"] = "C76.3", // Pelvis, BBT -> Pelvis, NOS (94)
        ["1077"] = "C16.3", // Gastrik antrum -> Gastric antrum (87)
        ["1304"] = "C74.1", // Adrenal bez medullası -> Medulla of adrenal gland (87)
        ["1068"] = "C15.2", // Abdominal özofagus -> Abdominal esophagus (86)
        ["1325"] = "C77.3", // Aksilla ya da kol lenf düğümleri -> Axillary lymph nodes / upper limb (81)
        ["1112"] = "C25.0", // Pankreas başı -> Head of pancreas (79)
        ["1071"] = "C15.5", // Özofagusun 1/3 alt bölümü -> Lower third of esophagus (77)
        ["1206"] = "C50.2", // Memenin üst-iç kadranı -> Upper-inner quadrant of breast (77)
        ["1085"] = "C17.2", // İleum -> Ileum (76)
        ["1186"] = "C47.4", // Abdomenin periferik ve otonom sinir sistemi -> Peripheral/autonomic nerves of abdomen (73)
        ["1144"] = "C37.9", // Timus -> Thymus (68)
        ["1319"] = "C76.5", // Alt ekstremite, BBT -> Lower limb, NOS (64)
        ["1193"] = "C49.2", // Alt ekstremite ve kalça bağ dokusu... -> Connective/soft tissue of lower limb, hip (64)
        ["1092"] = "C18.4", // Transvers kolon -> Transverse colon (61)
        ["1209"] = "C50.5", // Memenin alt-dış kadranı -> Lower-outer quadrant of breast (52)
        ["1136"] = "C32.9", // Larinks, BBT -> Larynx, NOS (52)
        ["1164"] = "C41.4", // Pelvik kemik, sakrum, koksiks... -> Pelvic bones, sacrum, coccyx (52)
        ["1075"] = "C16.1", // Mide fundusu -> Fundus of stomach (50)
        ["1235"] = "C57.4", // Uterin adneks -> Uterine adnexa (49)
        ["1170"] = "C42.2", // Dalak -> Spleen (49)
        ["1034"] = "C06.9", // Ağız, BBT -> Mouth, NOS (42)
        ["1211"] = "C50.8", // Memede aşan lezyon -> Overlapping lesion of breast (41)
        ["1326"] = "C77.4", // İnguinal bölge ya da bacak lenf düğümleri -> Inguinal lymph nodes / lower limb (41)
        ["1098"] = "C19.9", // Rektosigmoid bileşke -> Rectosigmoid junction (40)
        ["1056"] = "C11.9", // Nasofarinks, BBT -> Nasopharynx, NOS (40)
        ["1017"] = "C02.9", // Dil, BBT -> Tongue, NOS (38)
        ["1156"] = "C40.2", // Alt ekstremite uzun kemikleri... -> Long bones of lower limb (37)
        ["1162"] = "C41.2", // Vertebral kolon/Omurga -> Vertebral column (35)
        ["1205"] = "C50.1", // Memenin santral bölgesi -> Central portion of breast (33)
        ["1179"] = "C44.7", // Alt ekstremite ve kalça derisi -> Skin of lower limb, hip (30)
        ["1102"] = "C21.1", // Anal kanal -> Anal canal (30)
        ["1113"] = "C25.1", // Pankreas gövdesi -> Body of pancreas (27)
        ["1157"] = "C40.3", // Alt ekstremite kısa kemikleri... -> Short bones of lower limb (27)
        ["1177"] = "C44.5", // Gövde derisi -> Skin of trunk (26)
        ["1079"] = "C16.5", // Mide küçük kurvatur, BBT -> Lesser curvature of stomach, NOS (25)
        ["1318"] = "C76.4", // Üst ekstremite, BBT -> Upper limb, NOS (24)
        ["1145"] = "C38.0", // Kalp -> Heart (24)
        ["1089"] = "C18.0", // Çekum -> Cecum (23)
        ["1070"] = "C15.4", // Özofagusun 1/3 orta bölümü -> Middle third of esophagus (22)
        ["1080"] = "C16.6", // Mide büyük kurvatur, BBT -> Greater curvature of stomach, NOS (21)
        ["1154"] = "C40.0", // Üst ekstremite uzun kemikleri, skapula... -> Long bones of upper limb, scapula (21)
        ["1069"] = "C15.3", // Özofagusun 1/3 üst bölümü -> Upper third of esophagus (21)
        ["1192"] = "C49.1", // Üst ekstremite ve omuz bağ dokusu... -> Connective/soft tissue of upper limb, shoulder (21)
        ["1109"] = "C24.1", // Vater ampullası -> Ampulla of Vater (20)
        ["1200"] = "C48.0", // Retroperitoneum -> Retroperitoneum (20)
        ["1197"] = "C49.6", // Gövde bağ dokusu... BBT -> Connective/soft tissue of trunk, NOS (20)
        ["1104"] = "C21.8", // Rektum, anus ve anal kanalda aşan lezyon -> Overlapping lesion of rectum/anus/anal canal (19)
        ["1257"] = "C66.9", // Üreter -> Ureter (19)
        ["1228"] = "C54.9", // Korpus uteri -> Corpus uteri, NOS (19)
        ["1204"] = "C50.0", // Memebaşı -> Nipple (18)
        ["1074"] = "C16.0", // Kardia, BBT -> Cardia, NOS (16)
        ["1043"] = "C09.9", // Tonsil, BBT -> Tonsil, NOS (16)
        ["1084"] = "C17.1", // Jejunum -> Jejunum (16)
        ["1218"] = "C51.9", // Vulva, BBT -> Vulva, NOS (16)
        ["1111"] = "C24.9", // Safra yolları, BBT -> Biliary tract, NOS (15)
        ["1280"] = "C69.9", // Göz, BBT -> Eye, NOS (14)
        ["1324"] = "C77.2", // İntra-abdominal lenf düğümleri -> Intra-abdominal lymph nodes (14)
        ["1207"] = "C50.3", // Memenin alt-iç kadranı -> Lower-inner quadrant of breast (14)
        ["1203"] = "C48.8", // Retroperiton ve peritonda aşan lezyon -> Overlapping lesion of retroperitoneum/peritoneum (13)
        ["1035"] = "C07.9", // Parotis bezi -> Parotid gland (13)
        ["1165"] = "C41.8", // Kemik, eklem ve eklem kıkırdaklarında aşan lezyon -> Overlapping lesion of bone/joint/cartilage (12) !! GOZDEN GECIR
        ["1210"] = "C50.6", // Memenin aksiller kuyruğu -> Axillary tail of breast (12)
        ["1176"] = "C44.4", // Baş saçlı deri ve boyun derisi -> Skin of scalp and neck (11)
        ["1226"] = "C54.3", // Fundus uteri -> Fundus uteri (11)
        ["1142"] = "C34.8", // Akciğerde aşan lezyon -> Overlapping lesion of lung (11)
        ["1101"] = "C21.0", // Anus, BBT -> Anus, NOS (11)
        ["1091"] = "C18.3", // Kolonun hepatik fleksuru -> Hepatic flexure of colon (11)
        ["1194"] = "C49.3", // Toraks bağ dokusu... -> Connective/soft tissue of thorax (11)
        ["1155"] = "C40.1", // Üst ekstremite kısa kemikleri... -> Short bones of upper limb (10)
        ["1182"] = "C47.0", // Baş, yüz, boyun periferik ve otonom sinir sistemi -> Peripheral/autonomic nerves of head, face, neck (10)
        ["1293"] = "C72.1", // Kauda ekuina -> Cauda equina (10)
        ["1307"] = "C75.1", // Hipofiz bezi -> Pituitary gland (10)
        ["1009"] = "C00.9", // Dudak, BBT -> Lip, NOS (10)
        ["1114"] = "C25.2", // Pankreas kuyruğu -> Tail of pancreas (9)
        ["1052"] = "C11.1", // Nasofarinks posteriyör duvarı -> Posterior wall of nasopharynx (9)
        ["1163"] = "C41.3", // Kosta, sternum, klavikula... -> Rib, sternum, clavicle (9)
        ["1078"] = "C16.4", // Pilor -> Pylorus (9)
        ["1284"] = "C71.0", // Serebrum/beyin -> Cerebrum (8)
        ["1174"] = "C44.2", // Dış kulak -> Skin of ear and external auricular canal (8)
        ["1173"] = "C44.1", // Göz kapağı -> Skin of eyelid, including canthus (8)
        ["1260"] = "C67.2", // Mesane yan duvarı -> Lateral wall of bladder (8)
        ["1201"] = "C48.1", // Peritonun spesifik bölgeleri -> Specified parts of peritoneum (8) !! GOZDEN GECIR
        ["1031"] = "C06.1", // Ağız vestibülü -> Vestibule of mouth (7)
        ["1256"] = "C65.9", // Renal pelvis -> Renal pelvis (7)
        ["1024"] = "C04.9", // Ağız tabanı, BBT -> Floor of mouth, NOS (7)
        ["1320"] = "C76.7", // Diğer iyi tanımlanmamış bölgeler -> Other ill-defined sites (7)
        ["1239"] = "C58.9", // Plasenta -> Placenta (7)
        ["1081"] = "C16.8", // Midede aşan lezyon -> Overlapping lesion of stomach (7)
        ["1221"] = "C53.8", // Serviks uteride aşan lezyon -> Overlapping lesion of cervix uteri (6)
        ["1093"] = "C18.5", // Kolonun splenik fleksuru -> Splenic flexure of colon (6)
        ["1178"] = "C44.6", // Üst ekstremite ve omuz derisi -> Skin of upper limb and shoulder (6)
        ["1019"] = "C03.1", // Alt dişeti -> Lower gum (6)
        ["1122"] = "C26.9", // Gastrointestinal kanal, BBT -> Gastrointestinal tract, NOS (6)
        ["1306"] = "C75.0", // Parathyroid bezi -> Parathyroid gland (6)
        ["1141"] = "C34.3", // Alt lob, akciğer -> Lower lobe, lung (5)
        ["1327"] = "C77.5", // Pelvik lenf düğümü -> Pelvic lymph nodes (5)
        ["1216"] = "C51.8", // Vulvayı aşan lezyonlar -> Overlapping lesion of vulva (5)
        ["1036"] = "C08.0", // Submandibuler bez -> Submandibular gland (5)
        ["1245"] = "C63.2", // SKROTUMm, BBT -> Scrotum, NOS (4)
        ["1283"] = "C70.9", // Meninksler, BBT -> Meninges, NOS (4)
        ["1263"] = "C67.5", // Mesane boynu -> Bladder neck (4)
        ["1286"] = "C71.2", // Temporal lob -> Temporal lobe (4)
        ["1066"] = "C15.0", // Servikal özofagus -> Cervical esophagus (4)
        ["1175"] = "C44.3", // Yüzün diğer ve spesifiye edilmeyen bölgelerinin derisi -> Skin of other/unspecified face parts (4)
        ["1146"] = "C38.1", // Anteriyör mediasten -> Anterior mediastinum (3)
        ["1130"] = "C31.9", // Aksesuvar sinus, BBT -> Accessory sinus, NOS (3)
        ["1312"] = "C75.8", // Endokrin bezleri ve ilgili yapılarda aşan lezyon -> Overlapping lesion of endocrine glands (3)
        ["1236"] = "C57.7", // Kadın genital organların diğer spesifik bölgeleri -> Other specified parts of female genital organs (3) !! GOZDEN GECIR
        ["1276"] = "C69.6", // Orbita, BBT -> Orbit, NOS (3)
        ["1180"] = "C44.8", // Deride aşan lezyonlar -> Overlapping lesion of skin (3)
        ["1261"] = "C67.3", // Mesane anteriyor duvarı -> Anterior wall of bladder (3)
        ["1149"] = "C38.8", // Kalp, mediasten ve plevrada aşan lezyon -> Overlapping lesion of heart/mediastinum/pleura (3)
        ["1300"] = "C72.8", // Beyin ve merkez sinir sisteminde aşan lezyon -> Overlapping lesion of brain/CNS (3)
        ["1106"] = "C22.1", // İntrehepatik safra yolları -> Intrahepatic bile duct (3)
        ["1134"] = "C32.3", // Laringeal kıkırdak -> Laryngeal cartilage (3)
        ["1268"] = "C68.0", // Üretra -> Urethra (2)
        ["1049"] = "C10.8", // Orofarinksde aşan lezyon -> Overlapping lesion of oropharynx (2)
        ["1328"] = "C77.8", // Multipl bölgelerin lenf düğümleri -> Lymph nodes of multiple regions (2)
        ["1262"] = "C67.4", // Mesane posteriyor duvarı -> Posterior wall of bladder (2)
        ["1292"] = "C72.0", // Spinal Kord -> Spinal cord (2)
        ["1016"] = "C02.8", // Dilde aşan lezyon -> Overlapping lesion of tongue (2)
        ["1126"] = "C31.1", // Ethmoid sinüs -> Ethmoid sinus (2)
        ["1289"] = "C71.7", // Beyin sapı -> Brain stem (2)
        ["1271"] = "C68.9", // Üriner sistem, BBT -> Urinary system, NOS (2)
        ["1087"] = "C17.8", // İnce barsağı aşan lezyonlar -> Overlapping lesion of small intestine (2)
        ["1050"] = "C10.9", // Orofarinks, BBT -> Oropharynx, NOS (2)
        ["1139"] = "C34.1", // Üst lob, akciğer -> Upper lobe, lung (2)
        ["1063"] = "C14.0", // Farinks, BBT -> Pharynx, NOS (2)
        ["1123"] = "C30.0", // Nasal kavite -> Nasal cavity (2)
        ["1244"] = "C60.9", // Penis, BBT -> Penis, NOS (2)
        ["1030"] = "C06.0", // Yanak mukozası -> Cheek mucosa (2)
        ["1231"] = "C57.0", // Fallop tüpü -> Fallopian tube (2)
        ["1108"] = "C24.0", // Ekstrahepatik safra yolları -> Extrahepatic bile duct (1)
        ["1014"] = "C02.3", // Dilin 2/3 anteriyoru, BBT -> Anterior two-thirds of tongue, NOS (1)
        ["1214"] = "C51.1", // Labium minus -> Labium minus (1)
        ["1321"] = "C76.8", // İyi tanımlanmamış bölgede aşan lezyon -> Overlapping lesion of ill-defined sites (1)
        ["1028"] = "C05.8", // Damakta aşan lezyon -> Overlapping lesion of palate (1)
        ["1140"] = "C34.2", // Orta lob, akciğer -> Middle lobe, lung (1)
        ["1110"] = "C24.8", // Safra yollarında aşan lezyon -> Overlapping lesion of biliary tract (1)
        ["1010"] = "C01.9", // Dil tabanı, BBT -> Base of tongue (1)
        ["1252"] = "C63.7", // Diğer spesifiye edilebilen erkek genital organları -> Other specified parts of male genital organs (1) !! GOZDEN GECIR
        ["1227"] = "C54.8", // Korpus uteride aşan lezyon -> Overlapping lesion of corpus uteri (1)
        ["1161"] = "C41.1", // Mandibula -> Mandible (1)
        ["1055"] = "C11.8", // Nasofarinksde aşan lezyon -> Overlapping lesion of nasopharynx (1)
        ["1313"] = "C75.9", // Endokrin bez, BBT -> Endocrine gland, NOS (1)
        ["1039"] = "C08.9", // Büyük tükrük bezleri, BBT -> Major salivary gland, NOS (1)
        ["1067"] = "C15.1", // Torasik özofagus -> Thoracic esophagus (1)
        ["1062"] = "C13.9", // Hipofarinks, BBT -> Hypopharynx, NOS (1)
        ["1012"] = "C02.1", // Dilin sınırları -> Border of tongue (1)
        ["1215"] = "C51.0", // Klitoris -> Clitoris (1)
        ["1120"] = "C26.0", // Intestinal trakt, BBT -> Intestinal tract, NOS (1) !! GOZDEN GECIR
        ["1269"] = "C68.1", // Paraürertal bez -> Paraurethral gland (1)
        ["1005"] = "C00.4", // Alt dudak mukozası -> Lower lip, inner aspect (1)
        ["1026"] = "C05.1", // Yumuşak damak, BBT -> Soft palate, NOS (1)
        ["1290"] = "C71.8", // Beyinde aşan lezyon -> Overlapping lesion of brain (1)
        ["1042"] = "C09.8", // Tonsilde aşan lezyon -> Overlapping lesion of tonsil (1)
        ["1003"] = "C00.2", // Dış dudak, BBT -> External lip, NOS (1)
        ["1048"] = "C10.4", // Branchial yarık -> Branchial cleft (1)
        ["1045"] = "C10.1", // Epiglot anterior yüzey -> Anterior surface of epiglottis (1)
        ["1033"] = "C06.8", // Ağzın diğer ve spesifiye edilemeyen bölgelerinde aşan lezyon -> Overlapping lesion of mouth (1)
        ["1147"] = "C38.2", // Posteriyor mediasten -> Posterior mediastinum (1)
        ["1301"] = "C72.9", // Sinir sistemi, BBT -> Nervous system, NOS (1)
        ["1020"] = "C03.9", // Dişeti, BBT -> Gum, NOS (1)
        ["1117"] = "C25.7", // Pankreasın diğer spesifiye edilebilen bölgeleri -> Other specified parts of pancreas (1)
        ["1158"] = "C40.8", // Ekstremite kemikleri, eklemler ve eklem kıkırdaklarında aşan lezyon -> Overlapping lesion of limb bones/joints/cartilage (1) !! GOZDEN GECIR
        ["1323"] = "C77.1", // İntratorasik lenf düğümleri -> Intrathoracic lymph nodes (1)
        ["1037"] = "C08.1", // Sublingual bez -> Sublingual gland (1)
        ["1275"] = "C69.5", // Lakrimal bez -> Lacrimal gland (1)
        ["1029"] = "C05.9", // Damak/Palate, BBT -> Palate, NOS (1)
        ["1196"] = "C49.5", // Pelvis bağ dokusu, subkutan doku ve diğer yumuşak dokular -> Connective/soft tissue of pelvis (1)
        ["1213"] = "C51.2", // Labium majus -> Labium majus (1)
        ["1007"] = "C00.6", // Dudak komissür -> Commissure of lip (1)
        ["1001"] = "C00.0", // Üst dış dudak -> External upper lip (1)
        ["1237"] = "C57.8", // Kadın genital organlarında aşan lezyon -> Overlapping lesion of female genital organs (1)
        ["1124"] = "C30.1", // Orta kulak -> Middle ear (1)
        ["1058"] = "C13.0", // Postkrikoid bölge -> Postcricoid region (1)
        ["1011"] = "C02.0", // Dilin dorsal yüzü, BBT -> Dorsal surface of tongue, NOS (1)
    };

    // Bilinmeyen kodda BILEREK false doner -- tahmin yok, cagiran taraf Skip eder.
    public static bool TryGetIcdO3(string? skrsKodu, out string icdO3Kodu)
    {
        icdO3Kodu = "";
        if (string.IsNullOrWhiteSpace(skrsKodu)) return false;
        return SkrsToIcdO3.TryGetValue(skrsKodu.Trim(), out icdO3Kodu!);
    }

    public static int Count => SkrsToIcdO3.Count;
}
